#!/usr/bin/env bash

for (( i = 0; i < 10; i++ )); do
    stack runghc haskell_async.hs
done

for (( i = 0; i < 10; i++ )); do
    stack runghc haskell_sync.hs
done

for (( i = 0; i < 10; i++ )); do
    luna run --target luna_async.luna
done

for (( i = 0; i < 10; i++ )); do
    luna run --target luna_sync.luna
done

for (( i = 0; i < 10; i++ )); do
    node node_async.js
done

for (( i = 0; i < 10; i++ )); do
    node node_sync.js
done
